#!/usr/bin/env python3
"""
Hardcoded Timestomping Detection Report Generator
Generates formatted reports from hardcoded detection results.
"""

import os
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional


class TimestompReportGenerator:
    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.detection_results: Dict[str, Any] = {}

    def load_detection_results(self, results: Dict[str, Any]):
        self.detection_results = results

    def generate_text_report(self, output_file: Optional[str] = None) -> str:
        if not self.detection_results:
            return "No detection results available."

        metadata = self.detection_results.get("analysis_metadata", {})
        summary = self.detection_results.get("summary", {})

        critical = self.detection_results.get("critical_findings", [])
        high = self.detection_results.get("high_findings", [])
        medium = self.detection_results.get("medium_findings", [])

        report = []
        report.append("=" * 90)
        report.append("           TIMESTOMPING DETECTION FORENSIC REPORT")
        report.append("           Generated by Cyber Chakshu Hardcoded Detection Engine")
        report.append("=" * 90)
        report.append("")
        report.append(f"Analysis Date:      {metadata.get('analyzed_at', 'N/A')}")
        report.append(f"Output Directory:  {metadata.get('output_directory', 'N/A')}")
        report.append(
            f"Total Files Analyzed: {metadata.get('total_files_analyzed', 0)}"
        )
        report.append("")

        report.append("-" * 90)
        report.append("                              EXECUTIVE SUMMARY")
        report.append("-" * 90)
        report.append("")
        report.append(
            f"  [CRITICAL] Critical Findings:  {summary.get('critical_count', 0)}"
        )
        report.append(
            f"  [HIGH]     High Findings:       {summary.get('high_count', 0)}"
        )
        report.append(
            f"  [MEDIUM]   Medium Findings:     {summary.get('medium_count', 0)}"
        )
        report.append(
            f"  Total Suspicious Files:        {summary.get('total_suspicious', 0)}"
        )
        report.append(
            f"  Total Indicators:             {summary.get('total_indicators', 0)}"
        )
        report.append("")

        if critical:
            report.append("=" * 90)
            report.append("                    CRITICAL TIMESTOMPING INDICATORS")
            report.append("=" * 90)
            report.append("")
            for i, finding in enumerate(critical, 1):
                report.append(f"#{i} FILENAME: {finding['filename']}")
                report.append(f"    Severity:  {finding['severity']}")
                report.append(f"    Score:     {finding['score']}")
                report.append("")
                report.append("    DETECTED ANOMALIES:")
                for indicator in finding.get("indicators", []):
                    report.append(f"      [-] {indicator['description']}")
                    report.append(f"          Rule ID:     {indicator['rule_id']}")
                    report.append(f"          Severity:   {indicator['severity']}")
                    report.append(f"          Evidence:   {indicator['evidence']}")
                    if indicator.get("timestamp_value"):
                        report.append(
                            f"          Timestamp:  {indicator['timestamp_value']}"
                        )
                    if indicator.get("expected_value"):
                        report.append(
                            f"          Expected:   {indicator['expected_value']}"
                        )
                    if indicator.get("time_diff_seconds"):
                        diff_days = indicator["time_diff_seconds"] / 86400
                        report.append(f"          Time Diff:  {diff_days:.2f} days")
                    report.append(f"          Source:     {indicator['source_layer']}")
                    report.append("")

                if finding.get("si_created"):
                    report.append(f"    MFT $SI Created:   {finding['si_created']}")
                if finding.get("fn_created"):
                    report.append(f"    MFT $FN Created:   {finding['fn_created']}")
                if finding.get("usn_first_create"):
                    report.append(
                        f"    USN First Create: {finding['usn_first_create']}"
                    )
                report.append(
                    f"    Prefetch Exists:  {'Yes' if finding.get('has_prefetch') else 'No'}"
                )
                if finding.get("prefetch_count", 0) > 0:
                    report.append(f"    Prefetch Count:   {finding['prefetch_count']}")
                report.append(
                    f"    Amcache Entry:    {'Yes' if finding.get('has_amcache') else 'No'}"
                )
                report.append("")
                report.append("-" * 90)
                report.append("")

        if high:
            report.append("=" * 90)
            report.append("                      HIGH SEVERITY TIMESTOMPING INDICATORS")
            report.append("=" * 90)
            report.append("")
            for i, finding in enumerate(high[:20], 1):
                report.append(f"#{i} FILENAME: {finding['filename']}")
                report.append(f"    Severity:  {finding['severity']}")
                report.append(f"    Score:     {finding['score']}")
                report.append("")

                for indicator in finding.get("indicators", []):
                    report.append(f"    [-] {indicator['description']}")
                    if indicator.get("time_diff_seconds"):
                        diff_days = indicator["time_diff_seconds"] / 86400
                        report.append(f"        Time Diff: {diff_days:.2f} days")
                    report.append(f"        Source: {indicator['source_layer']}")
                report.append("")

        if medium:
            report.append("=" * 90)
            report.append("                    MEDIUM SEVERITY TIMESTOMPING INDICATORS")
            report.append("=" * 90)
            report.append("")
            for i, finding in enumerate(medium[:10], 1):
                report.append(f"#{i} {finding['filename']} (Score: {finding['score']})")
                for indicator in finding.get("indicators", [])[:2]:
                    report.append(f"    - {indicator['description']}")
            report.append("")

        report.append("=" * 90)
        report.append("                           DETECTION RULES APPLIED")
        report.append("=" * 90)
        report.append("")
        report.append("  Rule ID                  | Severity  | Description")
        report.append(
            "  -------------------------|-----------|------------------------------------------"
        )
        report.append(
            "  si_fn_mismatch           | HIGH      | $SI vs $FN timestamp mismatch"
        )
        report.append(
            "  si_usn_mismatch          | CRITICAL  | SI timestamp before USN creation"
        )
        report.append(
            "  si_logfile_mismatch      | HIGH      | SI differs from $LogFile transactions"
        )
        report.append(
            "  si_event_mismatch        | HIGH      | File created after latest event log"
        )
        report.append(
            "  future_timestamp         | CRITICAL  | Timestamp in the future"
        )
        report.append(
            "  zero_timestamp           | HIGH      | Zero/empty timestamps (1601)"
        )
        report.append(
            "  identical_timestamps     | HIGH      | All MACE timestamps identical"
        )
        report.append(
            "  prefetch_mismatch        | MEDIUM    | EXE without prefetch on active system"
        )
        report.append(
            "  usn_missing              | MEDIUM    | USN Journal missing/empty"
        )
        report.append(
            "  logfile_missing          | LOW       | $LogFile missing/no records"
        )
        report.append("")

        report.append("=" * 90)
        report.append("                              RECOMMENDATIONS")
        report.append("=" * 90)
        report.append("")

        if summary.get("critical_count", 0) > 0:
            report.append("  [!] IMMEDIATE ACTION REQUIRED")
            report.append("      - Critical timestomping indicators detected")
            report.append("      - Isolate system for further investigation")
            report.append(
                "      - Check for known timestomping tools (Timestomp, FAR, etc.)"
            )
            report.append("      - Review user account activity")
            report.append("")

        if summary.get("high_count", 0) > 0:
            report.append("  [!] HIGH PRIORITY INVESTIGATION")
            report.append("      - Multiple timestamp anomalies detected")
            report.append("      - Correlate with user activity logs")
            report.append("      - Check for unauthorized software installation")
            report.append("")

        if summary.get("medium_count", 0) > 0:
            report.append("  [~] MONITOR AND VERIFY")
            report.append("      - Review files for legitimate timestamp modifications")
            report.append("      - Document any authorized software updates")
            report.append("")

        report.append("  [+] Regular monitoring and baseline comparison recommended.")
        report.append("")
        report.append("=" * 90)
        report.append(f"Report generated at: {datetime.now().isoformat()}")
        report.append("=" * 90)

        report_text = "\n".join(report)

        if output_file:
            with open(output_file, "w") as f:
                f.write(report_text)
            print(f"    Report saved to: {output_file}")

        return report_text

    def generate_json_report(self, output_file: Optional[str] = None) -> Dict[str, Any]:
        if output_file:
            with open(output_file, "w") as f:
                json.dump(self.detection_results, f, indent=2, default=str)
            print(f"    JSON report saved to: {output_file}")

        return self.detection_results

    def generate_csv_report(self, output_file: Optional[str] = None) -> str:
        import csv
        from io import StringIO

        output = StringIO()
        writer = csv.writer(output)

        writer.writerow(
            [
                "Filename",
                "Severity",
                "Score",
                "Rule ID",
                "Description",
                "Timestamp Value",
                "Expected Value",
                "Time Diff (Days)",
                "Source Layer",
            ]
        )

        for finding in self.detection_results.get("all_suspicious", []):
            filename = finding.get("filename", "")
            severity = finding.get("severity", "")
            score = finding.get("score", 0)

            for indicator in finding.get("indicators", []):
                writer.writerow(
                    [
                        filename,
                        severity,
                        score,
                        indicator.get("rule_id", ""),
                        indicator.get("description", ""),
                        indicator.get("timestamp_value", ""),
                        indicator.get("expected_value", ""),
                        round(indicator.get("time_diff_seconds", 0) / 86400, 2)
                        if indicator.get("time_diff_seconds")
                        else "",
                        indicator.get("source_layer", ""),
                    ]
                )

        csv_content = output.getvalue()

        if output_file:
            with open(output_file, "w", newline="") as f:
                f.write(csv_content)
            print(f"    CSV report saved to: {output_file}")

        return csv_content

    def generate_summary_html(self, output_file: Optional[str] = None) -> str:
        metadata = self.detection_results.get("analysis_metadata", {})
        summary = self.detection_results.get("summary", {})
        critical = self.detection_results.get("critical_findings", [])
        high = self.detection_results.get("high_findings", [])

        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Cyber Chakshu Timestomping Report</title>
    <style>
        body {{ font-family: 'Courier New', monospace; margin: 40px; background: #1a1a1a; color: #e0e0e0; }}
        h1, h2, h3 {{ color: #00ff00; }}
        .header {{ background: #0d0d0d; padding: 20px; border: 2px solid #00ff00; margin-bottom: 20px; }}
        .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
        .stat {{ background: #0d0d0d; padding: 15px 25px; border-left: 4px solid #00ff00; }}
        .critical {{ border-color: #ff0000; color: #ff4444; }}
        .high {{ border-color: #ff8800; color: #ffaa00; }}
        .medium {{ border-color: #ffff00; color: #ffff00; }}
        .finding {{ background: #0d0d0d; padding: 15px; margin: 10px 0; border-left: 4px solid; }}
        .finding.critical {{ border-color: #ff0000; }}
        .finding.high {{ border-color: #ff8800; }}
        .finding.medium {{ border-color: #ffff00; }}
        .indicator {{ background: #222; padding: 8px; margin: 5px 0; font-size: 0.9em; }}
        .meta {{ color: #888; font-size: 0.8em; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #333; }}
        th {{ background: #0d0d0d; color: #00ff00; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Cyber Chakshu Timestomping Detection Report</h1>
        <p class="meta">Generated: {metadata.get("analyzed_at", "N/A")}</p>
        <p class="meta">Directory: {metadata.get("output_directory", "N/A")}</p>
    </div>
    
    <h2>Executive Summary</h2>
    <div class="summary">
        <div class="stat critical">CRITICAL: {summary.get("critical_count", 0)}</div>
        <div class="stat high">HIGH: {summary.get("high_count", 0)}</div>
        <div class="stat medium">MEDIUM: {summary.get("medium_count", 0)}</div>
        <div class="stat">Total Analyzed: {metadata.get("total_files_analyzed", 0)}</div>
    </div>
    
    <h2>Critical Findings</h2>
"""

        if critical:
            for finding in critical:
                html += f"""
    <div class="finding critical">
        <h3>{finding["filename"]}</h3>
        <p>Score: {finding["score"]} | Severity: {finding["severity"]}</p>
"""
                for ind in finding.get("indicators", []):
                    html += f"""
        <div class="indicator">
            <strong>{ind["description"]}</strong><br>
            <span class="meta">Rule: {ind["rule_id"]} | Source: {ind["source_layer"]}</span>
        </div>
"""
                html += "    </div>\n"
        else:
            html += "    <p>No critical findings.</p>\n"

        html += """
    <h2>High Severity Findings</h2>
"""

        if high:
            for finding in high[:10]:
                html += f"""
    <div class="finding high">
        <h3>{finding["filename"]}</h3>
        <p>Score: {finding["score"]}</p>
"""
                for ind in finding.get("indicators", [])[:2]:
                    html += f"""
        <div class="indicator">{ind["description"]}</div>
"""
                html += "    </div>\n"
        else:
            html += "    <p>No high severity findings.</p>\n"

        html += """
</body>
</html>
"""

        if output_file:
            with open(output_file, "w") as f:
                f.write(html)
            print(f"    HTML report saved to: {output_file}")

        return html


def generate_reports(
    output_dir: str, detection_results: Dict[str, Any]
) -> Dict[str, str]:
    """Generate all report formats"""
    generator = TimestompReportGenerator(output_dir)
    generator.load_detection_results(detection_results)

    output_path = Path(output_dir)

    reports = {}

    txt_file = output_path / "timestomp_report.txt"
    reports["text"] = str(txt_file)
    generator.generate_text_report(str(txt_file))

    json_file = output_path / "timestomp_report.json"
    reports["json"] = str(json_file)
    generator.generate_json_report(str(json_file))

    csv_file = output_path / "timestomp_report.csv"
    reports["csv"] = str(csv_file)
    generator.generate_csv_report(str(csv_file))

    html_file = output_path / "timestomp_report.html"
    reports["html"] = str(html_file)
    generator.generate_summary_html(str(html_file))

    return reports
